function [t m r] = extractData(raw)
% Process a line generated by the Arduino.
%
% Input:
%
%    raw: the raw line, as read from Arduino serial
%
% Output:
%
%     t: time
%     m: measure
%     r: ref
%
fields = split_string(raw, ';');
limit = length(fields);
t = [ ];
m = [ ];
r = [ ];

for n = 1:limit
    field = split_string(fields{n}, ' ');
    if length(field) == 3
        t(end+1) = str2num(field{1});
        m(end+1) = str2num(field{2});
        r(end+1) = str2num(field{3});
    end
end

function [outlet] = split_string(inlet, delim)
% Splits a string into a delimiter string.
%
%     [outlet] = split_string(inlet, delim);
%
% Creats a cell array `outlet` with the separated strings from `inlet` by
% `delim`.
% Taken from https://github.com/lab-neuro-comp/P2/blob/master/P2lib/util/split_string.m
%
outlet = tokenizeString(inlet, delim);

function [tokens] = tokenizeString(string,delimeter)
tokens = {};
while not(isempty(string))
    [tokens{end+1},string] = strtok(string,delimeter);
end
